on:
  push:
    branches:
      - master

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          toolchain: minimal
          default: true
      - uses: Swatinem/rust-cache@v1
      - run: make win
  release-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          target: aarch64-apple-darwin
          toolchain: minimal
          default: true
      - uses: Swatinem/rust-cache@v1
      - run: make mac