on:
  push:
    branches:
      - master

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          toolchain: stable
          profile: minimal
          default: true
      - uses: Swatinem/rust-cache@v1
      - run: make win
      - uses: actions/upload-artifact@v3
        with:
          name: windows-release
          path: dist/*.exe
  release-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Cargo Toolchain 🛎️
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          profile: minimal
          default: true
      - uses: Swatinem/rust-cache@v1
      - run: make osx
      - uses: actions/upload-artifact@v3
        with:
          name: mac-release
          path: dist/*.dmg